version: '3'
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./_clickhouse/data:/var/lib/clickhouse
      - ./_clickhouse/logs:/var/log/clickhouse-server
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "8002:9000"
      - "9123:8123"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE